# Generated by Django 5.0.7 on 2024-07-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dishId', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('dishName', models.CharField(max_length=100)),
                ('imageUrl', models.URLField(max_length=255)),
                ('isPublished', models.BooleanField(default=True)),
            ],
        ),
    ]
